project:
  type: website

website:
  title: "Quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Homepage
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



